### ISSUE TITLE
`npm run deploy` not possible with NPM two-factor authentication 

### ISSUE THREAD

**Issue by lievenvg** [digipolisantwerp/acpaas-ui_js#6]
## Describe the bug
Deployment isn't possible with NPM two-factor authentication and returns the following error:
`
lerna ERR! execute caught error
lerna ERR! Error: 
lerna ERR! src/index.js → ./dist/acpaas-ui-js-date-utils.amd.js, ./dist/acpaas-ui-js-date-utils.cjs.js, ./dist/acpaas-ui-js-date-utils.es.js, ./dist/acpaas-ui-js-date-utils.umd.js...
lerna ERR! created ./dist/acpaas-ui-js-date-utils.amd.js, ./dist/acpaas-ui-js-date-utils.cjs.js, ./dist/acpaas-ui-js-date-utils.es.js, ./dist/acpaas-ui-js-date-utils.umd.js in 1.4s
lerna ERR! 
lerna ERR!     at Function.module.exports.sync (.../acpaas-ui_js/node_modules/lerna/node_modules/execa/index.js:303:26)
lerna ERR!     at Function.execSync (.../acpaas-ui_js/node_modules/lerna/lib/ChildProcessUtilities.js:59:30)
lerna ERR!     at Function.runScriptInDirSync (.../acpaas-ui_js/node_modules/lerna/lib/NpmUtilities.js:198:39)
lerna ERR!     at Package.runScriptSync (.../acpaas-ui_js/node_modules/lerna/lib/Package.js:95:32)
lerna ERR!     at PublishCommand.runSyncScriptInPackage (.../acpaas-ui_js/node_modules/lerna/lib/commands/PublishCommand.js:632:11)
lerna ERR!     at .../acpaas-ui_js/node_modules/lerna/lib/commands/PublishCommand.js:745:17
lerna ERR!     at Array.forEach (<anonymous>)
lerna ERR!     at PublishCommand.commitAndTagUpdates (.../acpaas-ui_js/node_modules/lerna/lib/commands/PublishCommand.js:744:20)
lerna ERR!     at PublishCommand.execute (.../acpaas-ui_js/node_modules/lerna/lib/commands/PublishCommand.js:329:14)
{ Error: 
src/index.js → ./dist/acpaas-ui-js-date-utils.amd.js, ./dist/acpaas-ui-js-date-utils.cjs.js, ./dist/acpaas-ui-js-date-utils.es.js, ./dist/acpaas-ui-js-date-utils.umd.js...
created ./dist/acpaas-ui-js-date-utils.amd.js, ./dist/acpaas-ui-js-date-utils.cjs.js, ./dist/acpaas-ui-js-date-utils.es.js, ./dist/acpaas-ui-js-date-utils.umd.js in 1.4s`

`    at Function.module.exports.sync (.../acpaas-ui_js/node_modules/lerna/node_modules/execa/index.js:303:26)
    at Function.execSync (.../acpaas-ui_js/node_modules/lerna/lib/ChildProcessUtilities.js:59:30)
    at Function.runScriptInDirSync (.../acpaas-ui_js/node_modules/lerna/lib/NpmUtilities.js:198:39)
    at Package.runScriptSync (.../acpaas-ui_js/node_modules/lerna/lib/Package.js:95:32)
    at PublishCommand.runSyncScriptInPackage (.../acpaas-ui_js/node_modules/lerna/lib/commands/PublishCommand.js:632:11)
    at .../acpaas-ui_js/node_modules/lerna/lib/commands/PublishCommand.js:745:17
    at Array.forEach (<anonymous>)
    at PublishCommand.commitAndTagUpdates (.../acpaas-ui_js/node_modules/lerna/lib/commands/PublishCommand.js:744:20)
    at PublishCommand.execute (.../acpaas-ui_js/node_modules/lerna/lib/commands/PublishCommand.js:329:14)
    at PublishCommand._attempt (.../acpaas-ui_js/node_modules/lerna/lib/Command.js:377:21) exitCode: 1 }
`

## To Reproduce
1. Enable two-factor authentication in https://www.npmjs.com
2. Try to build and deploy a new version of `acpaas-ui_js`with `npm run deploy`.

## Expected behavior
New build and tags should be created and deployed.
But perhaps it's a better choice to split this into two separate actions: build and add tags / deploy new version.

## System
Device: MacBook Pro (Retina, 13-inch, Late 2013)
OS: macOS High Sierra (Version 10.13.6)
Node v8.9.4
NPM v5.6.0

**Comment by TriangleJuice** [comment]
Closing this issue as it is an issue with lerna, not our package. See:
- https://github.com/lerna/lerna/issues/1091
- https://github.com/lerna/lerna/issues/1137

Possible workaround (not tested):
`NPM_CONFIG_OTP=123456 npm run deploy`
